apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wontlost-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # Use git files generator to only include directories with kustomization.yaml
    - git:
        repoURL: https://github.com/wontlost-ltd/k3s.git
        revision: main
        files:
          - path: apps/wontlost/*/kustomization.yaml
  template:
    metadata:
      name: 'wontlost-{{ index .path.segments 2 }}'
      namespace: argocd
      labels:
        domain: wontlost.com
        app.kubernetes.io/part-of: wontlost
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: wontlost
      source:
        repoURL: https://github.com/wontlost-ltd/k3s.git
        targetRevision: main
        path: 'apps/wontlost/{{ index .path.segments 2 }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'wontlost-{{ index .path.segments 2 }}'
      ignoreDifferences:
        - group: external-secrets.io
          kind: ExternalSecret
          jqPathExpressions:
            - .spec.data[].remoteRef.conversionStrategy
            - .spec.data[].remoteRef.decodingStrategy
            - .spec.data[].remoteRef.metadataPolicy
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
